### ISSUE TITLE
TypeError: ct.getTimezone is not a function

### ISSUE THREAD

**Issue by marcusaaronb** [manuelmhtr/countries-and-timezones#65]
TypeError: ct.getTimezone is not a function
    at eval (index.js:13:1)
    at Array.forEach (<anonymous>)
    at _callee$ (index.js:11:1)
    at tryCatch (runtime.js:64:40)
    at Generator.invoke (runtime.js:300:22)
    at Generator.eval [as next] (runtime.js:124:21)
    at asyncGeneratorStep (asyncToGenerator.js:5:24)
    at _next (asyncToGenerator.js:24:9)

**Comment by manuelmhtr** [comment]
Hello @marcusaaronb could you share more information about the problem? like:
* how you are importing the module?
* your nodejs version?

**Comment by marcusaaronb** [comment]
Version: ^2.3.1
Node: v14.18.2
Importing: const ct = require('countries-and-timezones');

**Comment by ihor-zinchenko** [comment]
try `import { getAllTimezones, getAllCountries } from 'countries-and-timezones';`
